name: echoNav
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sslcommerz: ^2.3.6
  http: ^0.13.3
  speech_to_text: ^6.1.1
  flutter_tts: ^3.5.0
  dio: ^5.3.2
  camera: ^0.10.0+1
  supabase_flutter: ^2.1.0
  google_ml_kit: ^0.13.0
  crypto: ^3.0.2
  google_maps_flutter: ^2.2.3
  geolocator: ^10.0.0
  image: ^4.0.17
  audioplayers: ^1.1.1
  bloc: ^8.1.0


  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/image.jpg

  # Enable the Google Maps Flutter plugin
  plugin:
    platforms:
      android:
        package: com.google.android.libraries.maps
        pluginClass: GoogleMapsPlugin
      ios:
        pluginClass: FLTGoogleMapsPlugin
